version: '3'

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./vanillaPhpProject:/vanillaPhpProject
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    php:
        build:
            context: .
            dockerfile: ./Dockerfile
        volumes:
            - ./vanillaPhpProject:/vanillaPhpProject
        networks:
            - code-network
    mysql:
        container_name: db
        image: mysql:8
        networks:
            - code-network
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_USER: 'root'
            MYSQL_PASSWORD: 'root'
        volumes:
            - ./data:/var/lib/mysql
networks:
    code-network:
        driver: bridge
